-   id: clang-format
    name: clang-format
    description: Format files with ClangFormat.
    entry: check-clang-then-run -i
    language: python
    files: \.(c|cc|cxx|cpp|frag|glsl|h|hpp|hxx|ih|ispc|ipp|java|js|m|mm|proto|textproto|vert)$
    args: ['-fallback-style=none']
